# Edit from group_add:
# receivers:
#   otlp:
#     protocols:
#       grpc:
#         endpoint: 0.0.0.0:4317
#       http:
#         endpoint: 0.0.0.0:4318  # This is what perf_daemon needs
# exporters:
#   otlp/jaeger:  # Defined here as 'jaeger'
#     endpoint: jaeger:4317
#     tls:
#       insecure: true
#   logging:
#     loglevel: debug
#
# service:
#   pipelines:
#     traces:
#       receivers: [otlp]
#       processors: [batch]
#       exporters: [otlp/jaeger, logging]

receivers:
  otlp:
    protocols:
      http: { endpoint: "0.0.0.0:4318" }
exporters:
  debug: { verbosity: detailed }
  otlphttp:
    endpoint:  "http://jaeger:4318" # Jaeger OTLP ingest
    tls: { insecure: true }
processors:
  batch: { timeout: 1s, send_batch_size: 128 }
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]
      # exporters: [otlp/jaeger]

